# --------------------------
# Secret MySQL
# --------------------------
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mysql.secret.name }}
  labels:
    {{- include "sitevitrine.labels" . | nindent 4 }}
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.secret.rootPassword | quote }}
  MYSQL_USER: {{ .Values.mysql.secret.user | quote }}
  MYSQL_PASSWORD: {{ .Values.mysql.secret.password | quote }}
