# ==========================
# StorageClass EBS gp3
# ==========================
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.mysql.storageClass.name }}
  labels:
    {{- include "sitevitrine.labels" . | nindent 4 }}
provisioner: {{ .Values.mysql.storageClass.provisioner }}
volumeBindingMode: {{ .Values.mysql.storageClass.volumeBindingMode }}
parameters:
  csi.storage.k8s.io/fstype: {{ .Values.mysql.storageClass.fstype }}
  type: {{ .Values.mysql.storageClass.type }}
  encrypted: {{ .Values.mysql.storageClass.encrypted | quote }}
allowedTopologies:
  - matchLabelExpressions:
      - key: topology.ebs.csi.aws.com/zone
        values:
          - {{ .Values.mysql.storageClass.zone }}
